name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # JAVA
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # GO
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # SESL
      - name: Setup Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "seslUser=${{ secrets.SESL_USER }}" >> ~/.gradle/gradle.properties
          echo "seslToken=${{ secrets.SESL_TOKEN }}" >> ~/.gradle/gradle.properties

      # BUILD (КЛЮЧЕВОЙ ФИКС ЗДЕСЬ)
      - name: Build APK
        env:
          GOSUMDB: sum.golang.org
        run: ./gradlew assembleDebug --no-daemon

      # ARTIFACT
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
