name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "seslUser=${{ secrets.SESL_USER }}" >> ~/.gradle/gradle.properties
          echo "seslToken=${{ secrets.SESL_TOKEN }}" >> ~/.gradle/gradle.properties

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
